env:
  global:
    - CC_TEST_REPORTER_ID=2c0263d0730edc77654195955e1221cbfad01a4f3010dab476c3917769236fe2
    - GITHUB_REPO: "proustibat/tic-tac-toe"
    - secure: "qX0m4RRXd2iGse+uqyu3TpK3h3kRWtBpRpD5wCPpoRhu7Ug3OWHdfwNs8CUr4E9WhDndAbFj6v6W4toyYgBslkgHE1U1ZXeewSgZRkaiFU2TNZFaMViC6NfAjWA2cZXWEtoQa95zkVYgyIbnZxYxlOIKVfiFt0J8f47bo2OizsV3Bnr8FHVXwUxUoKxENwluXcg3i2e1BDI0ViRKednQqnTi0E98nKequNrm9qEscUlQYyqJon9s0k7zfPq0PHZ4RMnQi/clLQgggl8mJ6NlwjIt2Kg9NeSb7ZDOTvHEsLn3ELy6LGM6KwKgE06ywFq1bK++iu8XnBPH6qaNiajqjv7EFL1M/K7OcGf4uWH+Ctofni55pxbgBWcTfaIAqUHneCHqvtvoKVnFkFpO9oSPVEncr4EJM0qBKDR/pLHn4WIWI+zUvN663IypNcijoo3h7Rbqhwnyx6spythtka7G2KjxHXkR5/EZq8Lvk8QO5BlZaAXU6t8hBlFiqqC8R77tfm5t5AGdJGf3TEiX/uscf21niKZyznArgEdOJQbVgR/4vt1Cz0Kj2pBRORWO9D7qu333uFldaqyaHE29BbuKsibRshuolT1VAK2Ea+vNpFObUPHGinKUfLxvYKmEzzQ6/9P/29F2hcEJdOnJ4ku5EZgk3fKH6ehATmKFbTQNE9c="


language: node_js

node_js:
  - "8"

install:
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script:
  - yarn build


# Here we want to check out where we are.
# We only want to update Github Pages if we're building
# the master branch of the original repository, so we
# have to check $TRAVIS_PULL_REQUEST and $TRAVIS_BRANCH.
# If we are here, we run bash deploy.sh
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
